sonar.projectKey=VetGlobal
sonar.projectName=VetGlobal API
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=app/**/__init__.py,storage/**
sonar.python.version=3.11,3.12,3.13,3.14
